HW_coursework easy level task initial version
auvaraksin/HW_coursework pull request #1
Opened 2022-03-01 22:13 UTC by auvaraksin

HW_coursework easy level task initial version

2022-03-02 17:37 UTC, OlgaLugacheva requested changes

2022-03-02 17:37 UTC, OlgaLugacheva commented on src/pro/sky/Main.java
> +        return id;
интересное решение, но можно было вернуть просто employeeList[i], давай здесь и далее перепишем , чтобы не обращаться второй раз к массиву

2022-03-02 17:37 UTC, OlgaLugacheva commented on src/pro/sky/Main.java
> +        return id;
здесь также - вернуть сотрудника

2022-03-03 16:13 UTC, auvaraksin commented on src/pro/sky/Main.java
> +        return id;
Предложение принято, код переписан в version 1.0

2022-03-03 16:13 UTC, auvaraksin commented on src/pro/sky/Main.java
> +        return id;
Предложение принято, код переписан в version 1.0

2022-03-03 19:07 UTC, OlgaLugacheva approved these changes

2022-03-04 17:15 UTC, merged